# Numpy Quick Tour

Adapted from a python introduction by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

Numpy provides high-performance multidimensional array objects, and tools for working with these arrays. Their high performance make them very useful in  applications that need to handle large sets numeric arrays quickly; they can also be very useful for caching data.

In [ ]:
import numpy as np

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The shape of an array is a tuple of integers giving the size of the array along each dimension. 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Array initialized from a list
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array in place
print (a)                

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create an array from nested lists
print (b)

In [ ]:
print (b.shape)                   
print (b[0, 0], b[0, 1], b[1, 0])

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print (a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print (b)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print (e)

One of the key features of numpy is that you operate on large array of numbers without having to loop through each one.  Loops can be slow in Python because of the extra the cost, compared to compiled CPU-specific code, of going between the interpreted environment and the instructions executed by the CPU.

For example, if we want to do some arithmetic on a million numbers, it takes much longer go through all the overhead of fetching each one than it does to process the whole block as a numpy array:

In [ ]:
import numpy as np
from time import time

start_time = time()
rand_arr = np.random.random((10000000,))
print("Created numpy array of 10 million random elements", time() - start_time)

start_time = time()
for i in range(rand_arr.shape[0]):
    rand_arr[i] += 100
sum_arr = rand_arr.sum()
print("Increased all the elements one by one", time() - start_time)

start_time = time()
rand_arr += 100
sum_arr = rand_arr.sum()
print("Increased all the elements at once", time() - start_time)

As an aside: The timeit module can help for getting a sense of how fast a small chunk of code will run.  It works by evaluating python code and timing how long it takes to execute.

http://www.geeksforgeeks.org/timeit-python-examples/

In [ ]:
from timeit import timeit

setup = """
import numpy as np
rand_arr = np.random.random((1000000,))
"""
stmt1 = """
for i in range(rand_arr.shape[0]): 
    rand_arr[i] += 100
"""
stmt2 = """
rand_arr += 100
"""
# Timeit works by evaluating python statements and timing them.
print(timeit(stmt1,  setup, number=10))
print(timeit(stmt2,  setup, number=10))


### Array indexing

Numpy offers several ways to index into arrays.  https://scipy.github.io/old-wiki/pages/Cookbook/Indexing

Slicing: Like Python lists, numpy arrays can be sliced, but with a few more options. Since arrays may be multidimensional, you must specify a slice for each dimension of the array. Indexes are always in row, column order (not x, y).

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

A slice of an array is a view into the same data, so modifying it modified the original array.

In [ ]:
print (a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])

You can index arrays with arrays:

In [ ]:
print (a[[0, 2], [1, 3]])

*Boolean array indexing* lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)

In [ ]:
# We use boolean array indexing to construct an array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print (a[bool_idx])

# We can do all of the above in a single concise statement:
print (a[a > 2])

In [ ]:
# Boolean indexing can also be useful for counting elements that meet a certain criterion, because True resolves to 1, and False to zero, so summing a conditional expression results in the count:

print((a>2))
print((a>2).sum())

# You can also do things like zero out array elements using boolean arrays:

print(a * (a>2))

Here are some more about boolean array indexing:

https://docs.scipy.org/doc/numpy-1.10.0/user/basics.indexing.html

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype, or uses a default, when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. The default is a float64, which is often much larger then you need, so specifying a smaller data type for larger arrays can save memory. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.uint8)  # Force a particular datatype

print (x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Math functions

Basic mathematical functions operate elementwise on arrays, and are available as operator overloads (functions like \__add__ that implement the + operator):

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x.__add__(y))
print (x + y)
print (x - y)
print (x * y)

Numpy also provides many built in functions that opererate on arrays:

In [ ]:
print (np.sum(x))
print (np.sqrt(x))
print (np.std(x))

Numpy also supports many linear algebra operations, which treat arrays as vectors and matrices:

In [ ]:
import numpy as np
v = np.array([2, 4])
w = np.array([3, 6])

# Inner product of vectors:
print (v.dot(w))
print (np.dot(v, w))

For many of these functions, you can specify whether the operation is carried out on the whole array, or a specific axis:

In [ ]:
x = np.array([[1,2],[3,4]])
print (x)
print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
v = np.array([[1,2,3], [4, 5, 6]])
print (v)
print (v.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x * v  # Multiple x by v using broadcasting
print(y)

More information is availaable here: [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or  [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

### Numpy exercises

Let's get some practice with numpy by first loading some data.  We have some numeric data from the XML files - zip codes and revenues.  Using the code below, you can generate numpy array files - one is a simple one-dimensional array containing the total revenue per zip code.  The second is a two-dimensional array of zip codes and revenues from each return.

In [ ]:
import csv
import numpy as np

sample_text = ""
zip_codes = []
revenues = []

with open("all_data.txt") as f:
    dr = csv.DictReader(f, delimiter="\t")
    for d in dr:
        try:
            if len(d["revenue"]) > 0 and len(d["zip"]) == 5:
                zip_codes.append(int(d["zip"]))
                revenues.append(int(d["revenue"]))
        except Exception as ex:
            print(d, ex)

# Simple one-dimensional case - an array with just revenues, where array index is zip code
arr_size = max(zip_codes)+1
arr = np.zeros((arr_size, ))
for i in range(len(zip_codes)):
    z = zip_codes[i]
    if z > 0:
        arr[z] += revenues[i]
np.save("revenue_per_zip.npy", arr)

# Two-dimensional case - an array with zip codes and revenus
arr_multi = np.array([zip_codes, revenues])
np.save("zips_and_revenues.npy", arr_multi)

We can look at the revenues in matplotlib using some of the stats functions in numpy (see https://docs.scipy.org/doc/numpy/reference/routines.statistics.html):

In [ ]:
import matplotlib.pyplot as plt
# lets plots show up in notebook
%matplotlib inline  

In [ ]:
import numpy as np
arr = np.load("revenue_per_zip.npy")
# Ignore the zips with zero total revenue
arr = arr[arr>0]
print(arr.max())
print(arr.min())
print(arr.min())
print(np.std(arr))
print(arr.mean())
print(np.median(arr))

plt.hist(np.log10(arr))  # Try plotting without log10!

#### Question - what are the 5% and 95% percentiles of non-profits by revenue based on this data?

Now lets take a look at the two-dimensional array and looking at specific zip codes

In [ ]:
import numpy as np
arr = np.load("zips_and_revenues.npy")
print(arr.shape)
print(arr)
arr = arr.T  # Transpose will set things up with more intuitive row/colums order
print(arr)

In [ ]:
print(arr[:, 0].max())
print(arr[:, 1].max())
# A couple of boolean array indexing examples:
arr[arr[:,1] == arr[:, 1].max()]
arr[arr[:,0] == 10003].sum()

### Question - in what zip codes are the top 0.01 percent of recipiences by revenue located?

#### Extra challenge 

Often, when processing text, we need to convert it to a numeric representation in a numpy array.  "Vectorizing" refers to expressing things like word frequencies as vectors, or 1-dimensional numpy arrays.  Taking the results of the last NLTK exercise, where we have the differences in word frequencies between NYC and NYS mission statements, convert those values into a numpy array.  Then use them as weights to classify any text that uses those words.  The steps might be something like:

* Create a list of word indexes and delta values.
* Convert the list of deltas into a numpy array.
* Create a numpy array of zeros the same size as the deltas.
* Take the text to classify and set the empty array values to 1 at the indexes corresponding to each word. 
* Calculate the dot product (sum of products) of the two arrays. 
* Based on the results, decide whether or not the text is likely to be from NYC or NYS.

In [ ]:
import nltk
from nltk.corpus.reader import PlaintextCorpusReader
nyc = PlaintextCorpusReader("./", "./nyc.txt")
nys = PlaintextCorpusReader("./", "./nys.txt")

nyc_counts  = nltk.FreqDist(nyc.words("./nyc.txt"))
nys_counts  = nltk.FreqDist(nyc.words("./nys.txt"))

words = list(set(nyc.words("./nyc.txt")))
########### Your code here ############


 ### A possible answer to question 1:

In [ ]:
top_zips = arr[arr[:, 1] > np.percentile(arr[:, 1], 99.99)]
print(top_zips)